@echo off
echo Creating virtual environment...
python -m venv .venv
echo Installing dependencies...
.venv\Scripts\python.exe -m pip install --upgrade pip
.venv\Scripts\python.exe -m pip install -r requirements.txt
echo Training model...
.venv\Scripts\python.exe train_model.py
echo Starting application...
.venv\Scripts\python.exe app.py
pause
